import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  FiCheckCircle,
  FiXCircle,
  FiUser,
  FiDollarSign,
  FiTrendingUp,
  FiHome,
  FiBriefcase,
  FiDownload,
} from "react-icons/fi";
import jsPDF from "jspdf";

const infoConfig = [
  { key: "Age", label: "Age", icon: FiUser, suffix: "" },
  { key: "Annual_Income", label: "Annual Income", icon: FiDollarSign, suffix: " USD" },
  { key: "Credit_Score", label: "Credit Score", icon: FiTrendingUp, suffix: "" },
  { key: "Loan_Amount", label: "Loan Amount", icon: FiHome, suffix: " USD" },
  { key: "Employment_Years", label: "Employment Years", icon: FiBriefcase, suffix: " yrs" },
];

export default function PredictionCard({ result, applicant }) {
  if (!result) return null;

  const isApproved = result.prediction === 1;
  const probabilityPct = Math.round(result.probability * 100);

  const handleDownloadPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.setTextColor(26, 103, 245);
    doc.text("Loan Approval Prediction Report", 14, 20);

    doc.setDrawColor(26, 103, 245);
    doc.line(14, 24, 196, 24);

    doc.setFontSize(13);
    doc.setTextColor(0, 0, 0);
    doc.text(`Status: ${isApproved ? "Approved" : "Denied"}`, 14, 36);
    doc.text(`Approval Probability: ${probabilityPct}%`, 14, 44);

    doc.setFontSize(12);
    doc.text("Applicant Information:", 14, 58);

    let y = 66;
    infoConfig.forEach(({ key, label, suffix }) => {
      doc.text(`${label}: ${applicant[key]}${suffix}`, 14, y);
      y += 8;
    });

    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(
      "Generated by Loan Approval Prediction System - React + Flask + Logistic Regression",
      14,
      y + 10
    );

    doc.save("loan_prediction_report.pdf");
  };

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={isApproved ? "approved" : "denied"}
        initial={{ opacity: 0, y: 30, scale: 0.96 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: -20 }}
        transition={{ duration: 0.45, ease: "easeOut" }}
        className="glass-card shadow-glass rounded-3xl p-6 sm:p-8 w-full"
      >
        <div className="flex flex-col items-center text-center gap-3">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: "spring", stiffness: 200, damping: 12, delay: 0.1 }}
            className={`w-16 h-16 rounded-full flex items-center justify-center ${
              isApproved
                ? "bg-emerald-100 dark:bg-emerald-900/40"
                : "bg-red-100 dark:bg-red-900/40"
            }`}
          >
            {isApproved ? (
              <FiCheckCircle className="text-emerald-500" size={34} />
            ) : (
              <FiXCircle className="text-red-500" size={34} />
            )}
          </motion.div>

          <h3
            className={`text-2xl font-bold ${
              isApproved
                ? "text-emerald-600 dark:text-emerald-400"
                : "text-red-600 dark:text-red-400"
            }`}
          >
            {isApproved ? "Approved" : "Denied"}
          </h3>
          <p className="text-slate-500 dark:text-slate-400 text-sm">
            Based on the Logistic Regression model prediction
          </p>
        </div>

        {/* Probability bar */}
        <div className="mt-6">
          <div className="flex justify-between text-sm font-semibold text-slate-600 dark:text-slate-300 mb-1.5">
            <span>Approval Probability</span>
            <span>{probabilityPct}%</span>
          </div>
          <div className="w-full h-3 rounded-full bg-slate-200 dark:bg-slate-700 overflow-hidden">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${probabilityPct}%` }}
              transition={{ duration: 0.8, ease: "easeOut" }}
              className={`h-full rounded-full ${
                isApproved
                  ? "bg-gradient-to-r from-emerald-400 to-emerald-600"
                  : "bg-gradient-to-r from-red-400 to-red-600"
              }`}
            />
          </div>
        </div>

        {/* Applicant details */}
        <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-3">
          {infoConfig.map(({ key, label, icon: Icon, suffix }) => (
            <div
              key={key}
              className="flex items-center gap-3 bg-white/70 dark:bg-slate-800/60 rounded-xl px-4 py-3 border border-slate-100 dark:border-slate-700"
            >
              <div className="w-9 h-9 rounded-lg bg-brand-50 dark:bg-slate-700 flex items-center justify-center shrink-0">
                <Icon className="text-brand-500" size={16} />
              </div>
              <div className="min-w-0">
                <p className="text-xs text-slate-400 dark:text-slate-500">{label}</p>
                <p className="text-sm font-semibold text-slate-800 dark:text-slate-100 truncate">
                  {applicant[key]}
                  {suffix}
                </p>
              </div>
            </div>
          ))}
        </div>

        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleDownloadPDF}
          className="mt-6 w-full flex items-center justify-center gap-2 bg-brand-900 hover:bg-brand-950 dark:bg-brand-700 dark:hover:bg-brand-800 text-white font-semibold py-3 rounded-xl transition-all"
        >
          <FiDownload size={18} />
          Download Report as PDF
        </motion.button>
      </motion.div>
    </AnimatePresence>
  );
}
